services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel --no-autoupdate run
    volumes:
      - ./cloudflared:/etc/cloudflared
    network_mode: host
